export const categories = [
  {
    id: 'breakfast',
    label: 'Breakfast',
    icon: '🍳',
    searchTags: [
      'Masala Dosa',
      'Eggs Benedict',
      'Belgian Waffles',
      'Uttapam Platter',
      'Avocado Toast',
      'Bircher Muesli',
      'English Breakfast',
      'South Indian Platter',
      'Pancake Stack',
      'Akuri on Toast',
    ],
    enabled: true,
  },
  {
    id: 'appetizers',
    label: 'Appetizers',
    icon: '🥪',
    searchTags: [
      'Crispy Calamari',
      'Bruschetta',
      'Dim Sum Basket',
      'Paneer Tikka',
      'Buffalo Wings',
      'Mezze Platter',
      'Tempura Prawns',
      'Spinach & Artichoke Dip',
      'Chicken Satay',
      'Loaded Nachos',
    ],
    enabled: true,
  },
  {
    id: 'soups_salads',
    label: 'Soups & Salads',
    icon: '🥗',
    searchTags: [
      'Classic Caesar Salad',
      'Tom Yum Soup',
      'Greek Salad',
      'Wild Mushroom Soup',
      'Quinoa Buddha Bowl',
      'Seafood Chowder',
      'Caprese Salad',
      'Lentil Soup',
      'Cobb Salad',
      'Miso Soup',
    ],
    enabled: true,
  },
  {
    id: 'indian_main_course',
    label: 'Local Favourite',
    icon: '👨‍🍳',
    searchTags: [
      'Butter Chicken',
      'Paneer Butter Masala',
      'Dal Makhani',
      'Biryani',
      'Rogan Josh',
      'Palak Paneer',
      'Fish Curry',
      'Chole Bhature',
      'Mixed Vegetable Curry',
      'Chicken Tikka Masala',
    ],
    enabled: true,
  },
  {
    id: 'continental_main_course',
    label: 'Continental',
    icon: '🍝',
    searchTags: [
      'Grilled Salmon',
      'Beef Tenderloin',
      'Mushroom Risotto',
      'Chicken Confit',
      'Ratatouille',
      'Sea Bass',
      'Vegetable Lasagna',
      'Pork Chops',
      'Gnocchi',
      'Duck Confit',
    ],
    enabled: true,
  },
  {
    id: 'asian_specialties',
    label: 'Asian Specialties',
    icon: '🥢',
    searchTags: [
      'Pad Thai',
      'Sushi Platter',
      'Kung Pao Chicken',
      'Vietnamese Pho',
      'Korean Bibimbap',
      'Mapo Tofu',
      'Malaysian Laksa',
      'Dimsum Platter',
      'Japanese Ramen',
      'Thai Green Curry',
    ],
    enabled: true,
  },
  {
    id: 'pizza_pasta',
    label: 'Pizza & Pasta',
    icon: '🍕',
    searchTags: [
      'Margherita Pizza',
      'Pepperoni Pizza',
      'Penne Arrabbiata',
      'Fettuccine Alfredo',
      'BBQ Chicken Pizza',
      'Seafood Pasta',
      'Four Cheese Pizza',
      'Pesto Pasta',
      'Supreme Pizza',
      'Lasagna',
    ],
    enabled: true,
  },
  {
    id: 'desserts',
    label: 'Desserts',
    icon: '🍰',
    searchTags: [
      'Tiramisu',
      'Chocolate Lava Cake',
      'Crème Brûlée',
      'Apple Pie',
      'Cheesecake',
      'Ice Cream Selection',
      'Gulab Jamun',
      'Fruit Pavlova',
      'Belgian Waffle',
      'Sticky Toffee Pudding',
    ],
    enabled: true,
  },
  {
    id: 'beverages',
    label: 'Beverages',
    icon: '🥤',
    searchTags: [
      'Fresh Fruit Juices',
      'Specialty Coffee',
      'Classic Mojito',
      'Smoothies',
      'Iced Teas',
      'Lassi',
      'Milkshakes',
      'Virgin Colada',
      'Mineral Water',
      'Soft Drinks',
    ],
    enabled: true,
  },
];
