export const categories = [
  {
    id: 'breakfast',
    label: 'Breakfast',
    icon: '🍳',
    enabled: true,
    searchTags: [
      'Masala Dosa',
      'Paneer Paratha',
      'Akuri Pav',
      'Idli Sambar',
      'Bombay Sandwich',
      'Aloo Poha',
      'Chole Bhature',
      'Medu Vada',
      'Keema Pav',
      'Eggs Benedict',
    ],
  },
  {
    id: 'healthy_choices',
    label: 'Healthy Choices',
    icon: '🥗',
    enabled: true,
    searchTags: [
      'Quinoa Salad',
      'Grilled Chicken Salad',
      'Fruit Bowl',
      'Sprouted Moong Salad',
      'Vegetable Soup',
      'Grilled Fish',
      'Lentil Soup',
      'Steamed Vegetables',
      'Chicken Breast Grilled',
      'Avocado Toast',
    ],
  },
  {
    id: 'soups_salads',
    label: 'Soups & Salads',
    icon: '🥗',
    enabled: true,
    searchTags: [
      'Mulligatawny Soup',
      'Tomato Shorba',
      'Kachumber Salad',
      'Paneer Tikka Salad',
      'Dal Shorba',
      'Sprouted Moong Salad',
      'Beetroot Raita',
      'Sweet Corn Spinach Soup',
      'Classic Caesar Salad',
      'Tom Yum Soup',
    ],
  },
  {
    id: 'local_favourite',
    label: 'Local Favourite',
    icon: '👨‍🍳',
    enabled: true,
    searchTags: [
      'Butter Chicken',
      'Paneer Butter Masala',
      'Dal Makhani',
      'Hyderabadi Biryani',
      'Rogan Josh',
      'Palak Paneer',
      'Fish Curry',
      'Chole Bhature',
      'Chicken Tikka Masala',
      'Mutton Vindaloo',
    ],
  },
  {
    id: 'continental',
    label: 'Continental',
    icon: '🍝',
    enabled: true,
    searchTags: [
      'Grilled Salmon',
      'Beef Tenderloin',
      'Mushroom Risotto',
      'Chicken Cordon Bleu',
      'Ratatouille',
      'Sea Bass',
      'Vegetable Lasagna',
      'Pork Chops',
      'Gnocchi',
      'Duck Confit',
    ],
  },
  {
    id: 'asian',
    label: 'Asian Specialties',
    icon: '🥢',
    enabled: true,
    searchTags: [
      'Chicken Manchurian',
      'Veg Schezwan',
      'Chili Paneer',
      'Hakka Noodles',
      'Schezwan Fried Rice',
      'Vegetable Spring Roll',
      'Peking Duck',
      'Dim Sum',
      'Hot and Sour Soup',
      'Thai Green Curry',
    ],
  },
  {
    id: 'pizza_pasta',
    label: 'Pizza & Pasta',
    icon: '🍕',
    enabled: true,
    searchTags: [
      'Tandoori Chicken Pizza',
      'Paneer Tikka Pizza',
      'Butter Chicken Pizza',
      'Masala Margherita',
      'Spicy Lamb Pizza',
      'Masala Alfredo',
      'Paneer Penne',
      'Chicken Lasagna',
      'Margherita Pizza',
      'Spaghetti Carbonara',
    ],
  },
  {
    id: 'kids_menu',
    label: 'Kids Menu',
    icon: '🧸',
    enabled: true,
    searchTags: [
      'Mini Cheese Pizza',
      'Chicken Nuggets',
      'Mac & Cheese',
      'Mini Burger',
      'Pasta Alfredo',
      'Grilled Cheese Sandwich',
      'French Fries',
      'Mini Pancakes',
      'Fruit Salad',
      'Chicken Sausages',
    ],
  },
  {
    id: 'appetizers',
    label: 'Appetizers',
    icon: '🥪',
    enabled: true,
    searchTags: [
      'Chicken Tikka',
      'Paneer Tikka',
      'Seekh Kebab',
      'Hara Bhara Kebab',
      'Fish Amritsari',
      'Tandoori Prawns',
      'Buffalo Wings',
      'Bruschetta',
      'Calamari',
      'Dim Sum',
    ],
  },
  {
    id: 'snacks',
    label: 'Snacks',
    icon: '🍟',
    enabled: true,
    searchTags: [
      'Samosa',
      'Pani Puri',
      'Aloo Tikki',
      'Paneer Pakora',
      'Chicken 65',
      'Masala Peanuts',
      'Onion Bhaji',
      'Corn Chaat',
      'Veg Spring Roll',
      'French Fries',
    ],
  },
  {
    id: 'street_food',
    label: 'Street Food',
    icon: '🌯',
    enabled: true,
    searchTags: [
      'Pav Bhaji',
      'Vada Pav',
      'Bhel Puri',
      'Sev Puri',
      'Dabeli',
      'Frankie Roll',
      'Kachori',
      'Pani Puri',
      'Chicken Shawarma',
      'Masala Corn',
    ],
  },
  {
    id: 'biryani_rice',
    label: 'Biryani & Rice',
    icon: '🍚',
    enabled: true,
    searchTags: [
      'Hyderabadi Biryani',
      'Veg Biryani',
      'Mutton Biryani',
      'Paneer Pulao',
      'Jeera Rice & Dal',
      'Kashmiri Pulao',
      'Chicken Fried Rice',
      'Lemon Rice',
      'Masala Khichdi',
      'Fried Rice',
    ],
  },
  {
    id: 'breads',
    label: 'Breads',
    icon: '🥖',
    enabled: true,
    searchTags: [
      'Butter Naan',
      'Garlic Naan',
      'Laccha Paratha',
      'Tandoori Roti',
      'Missi Roti',
      'Roomali Roti',
      'Stuffed Kulcha',
      'Cheese Naan',
      'Pita Bread',
      'Focaccia',
    ],
  },
  {
    id: 'desserts',
    label: 'Desserts',
    icon: '🍰',
    enabled: true,
    searchTags: [
      'Gulab Jamun',
      'Ras Malai',
      'Kheer',
      'Jalebi',
      'Kulfi',
      'Gajar Halwa',
      'Chocolate Brownie',
      'Cheesecake',
      'Tiramisu',
      'Crème Brûlée',
    ],
  },
  {
    id: 'beverages',
    label: 'Beverages',
    icon: '🥤',
    enabled: true,
    searchTags: [
      'Masala Chai',
      'Filter Coffee',
      'Lassi',
      'Jaljeera',
      'Nimbu Pani',
      'Thandai',
      'Masala Soda',
      'Ginger Tea',
      'Cappuccino',
      'Mojito',
    ],
  },
  {
    id: 'cocktails',
    label: 'Cocktails',
    icon: '🍸',
    enabled: true,
    searchTags: [
      'Masala Mojito',
      'Tamarind Margarita',
      'Mango Mule',
      'Spiced Gin Tonic',
      'Rose Martini',
      'Indian Punch',
      'Coconut Cooler',
      'Aam Panna Punch',
      'Kala Khatta Margarita',
      'Saffron Sour',
    ],
  },
];
