export const menuItems = [
  {
    category: 'breakfast',
    items: [
      {
        name: 'Masala Dosa',
        description:
          'Crispy rice crepe filled with spiced potatoes, served with sambar and chutneys.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 120,
        popular: true,
      },
      {
        name: 'Paneer Paratha',
        description:
          'Whole wheat flatbread stuffed with spiced cottage cheese, served with yogurt.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 140,
        popular: true,
      },
      {
        name: 'Akuri Pav',
        description: 'Spiced Parsi-style scrambled eggs on buttered bread.',
        is_veg: false,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 160,
        popular: true,
      },
      {
        name: 'Idli Sambar',
        description:
          'Steamed rice cakes served with sambar and coconut chutney.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 110,
        popular: true,
      },
      {
        name: 'Bombay Sandwich',
        description:
          'Multi-layered sandwich with mint chutney and fresh vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 130,
        popular: true,
      },
      {
        name: 'Aloo Poha',
        description:
          'Flattened rice cooked with mustard seeds, peanuts, and lemon.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 100,
        popular: false,
      },

      {
        name: 'Medu Vada',
        description: 'Crispy lentil doughnuts served with sambar and chutney.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 120,
        popular: false,
      },
      {
        name: 'Keema Pav',
        description: 'Minced spiced meat served with buttered buns.',
        is_veg: false,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 180,
        popular: false,
      },
      {
        name: 'Eggs Benedict',
        description: 'Poached eggs on muffin with hollandaise sauce.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: false,
      },
      {
        name: 'French Toast',
        description: 'Bread soaked in egg batter, fried and served with syrup.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Croissant',
        description: 'Buttery flaky French pastry.',
        is_veg: true,
        available_24h: false,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 150,
        popular: false,
      },
    ],
  },
  {
    category: 'healthy_choices',
    items: [
      {
        name: 'Quinoa Salad',
        description: 'Fresh quinoa with vegetables and lemon dressing.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 250,
        popular: true,
      },
      {
        name: 'Grilled Chicken Salad',
        description:
          'Mixed greens topped with grilled chicken and vinaigrette.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 300,
        popular: true,
      },
      {
        name: 'Fruit Bowl',
        description: 'Seasonal fresh fruits served chilled.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: true,
      },
      {
        name: 'Sprouted Moong Salad',
        description: 'Sprouted lentils with lemon juice and chaat masala.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 150,
        popular: true,
      },
      {
        name: 'Vegetable Soup',
        description: 'Light broth with mixed seasonal vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Grilled Fish',
        description: 'Herb-marinated fish grilled to perfection.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 400,
        popular: false,
      },
      {
        name: 'Lentil Soup',
        description: 'Protein-rich lentil soup with mild spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Steamed Vegetables',
        description: 'Fresh seasonal vegetables steamed lightly.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: false,
      },
      {
        name: 'Chicken Breast Grilled',
        description: 'Lean grilled chicken breast with herbs.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Avocado Toast',
        description: 'Whole wheat toast topped with mashed avocado.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Greek Yogurt Parfait',
        description: 'Layered yogurt with fresh fruits and granola.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 200,
        popular: false,
      },
      {
        name: 'Baked Sweet Potato',
        description: 'Sweet potato baked with herbs and spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: false,
      },
    ],
  },
  {
    category: 'soups_salads',
    items: [
      {
        name: 'Mulligatawny Soup',
        description: 'Spiced Indian lentil soup with vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: true,
      },
      {
        name: 'Tomato Shorba',
        description: 'Light spiced tomato soup.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 160,
        popular: true,
      },
      {
        name: 'Kachumber Salad',
        description: 'Fresh cucumber, tomato, onion with chaat masala.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 140,
        popular: true,
      },
      {
        name: 'Paneer Tikka Salad',
        description: 'Grilled paneer cubes on mixed greens.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 250,
        popular: true,
      },
      {
        name: 'Dal Shorba',
        description: 'Light lentil broth with mild spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Beetroot Raita',
        description: 'Yogurt salad with grated beetroot.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 140,
        popular: false,
      },
      {
        name: 'Sweet Corn Spinach Soup',
        description: 'Sweet corn and spinach soup with spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 170,
        popular: false,
      },
      {
        name: 'Mango Cucumber Salad',
        description: 'Fresh mango and cucumber with mint.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Classic Caesar Salad',
        description: 'Romaine lettuce with parmesan and croutons.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Tom Yum Soup',
        description: 'Spicy Thai sour soup with mushrooms.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 200,
        popular: false,
      },
      {
        name: 'Greek Salad',
        description: 'Tomatoes, cucumbers, olives, and feta cheese.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 230,
        popular: false,
      },
    ],
  },
  {
    category: 'local_favourite',
    items: [
      {
        name: 'Butter Chicken',
        description: 'Creamy tomato butter chicken.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 340,
        popular: true,
      },
      {
        name: 'Paneer Butter Masala',
        description: 'Cottage cheese in creamy tomato gravy.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: true,
      },
      {
        name: 'Dal Makhani',
        description: 'Slow-cooked black lentils.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 260,
        popular: true,
      },
      {
        name: 'Hyderabadi Biryani',
        description: 'Spiced chicken or lamb biryani.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 360,
        popular: true,
      },
      {
        name: 'Rogan Josh',
        description: 'Spiced lamb curry.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 360,
        popular: true,
      },
      {
        name: 'Palak Paneer',
        description: 'Spinach and cottage cheese curry.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 270,
        popular: false,
      },
      {
        name: 'Fish Curry',
        description: 'Tangy fish curry with spices.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Chole Bhature',
        description: 'Spicy chickpea curry with fried bread.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Chicken Tikka Masala',
        description: 'Grilled chicken in tomato gravy.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 340,
        popular: false,
      },
      {
        name: 'Mutton Vindaloo',
        description: 'Hot and tangy mutton curry.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 370,
        popular: false,
      },
      {
        name: 'Paneer Lababdar',
        description: 'Paneer cooked in rich tomato and cashew gravy.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Malai Kofta',
        description: 'Vegetable dumplings in creamy sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 290,
        popular: false,
      },
    ],
  },
  {
    category: 'continental',
    items: [
      {
        name: 'Grilled Salmon',
        description: 'Salmon grilled with herbs and butter.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 450,
        popular: false,
      },
      {
        name: 'Beef Tenderloin',
        description: 'Grilled beef with pepper sauce.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 480,
        popular: false,
      },
      {
        name: 'Mushroom Risotto',
        description: 'Creamy Italian rice with mushrooms.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Chicken Cordon Bleu',
        description: 'Breaded chicken stuffed with cheese and ham.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 400,
        popular: false,
      },
      {
        name: 'Ratatouille',
        description: 'French vegetable stew.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Sea Bass',
        description: 'Pan-seared sea bass with lemon butter.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 470,
        popular: false,
      },
      {
        name: 'Vegetable Lasagna',
        description: 'Layered pasta with vegetables and cheese.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Pork Chops',
        description: 'Grilled pork chops with herbs.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 480,
        popular: false,
      },
      {
        name: 'Gnocchi',
        description: 'Potato dumplings with tomato sauce.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 300,
        popular: false,
      },
      {
        name: 'Duck Confit',
        description: 'Slow cooked duck leg with spices.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 550,
        popular: false,
      },
      {
        name: 'Masala Gnocchi',
        description: 'Potato dumplings in spiced tomato sauce.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 300,
        popular: false,
      },
      {
        name: 'Chicken Alfredo Pasta',
        description: 'Creamy pasta with spiced chicken.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 350,
        popular: false,
      },
    ],
  },
  {
    category: 'asian',
    items: [
      {
        name: 'Chicken Manchurian',
        description: 'Spicy fried chicken in tangy Indo-Chinese sauce.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 300,
        popular: true,
      },
      {
        name: 'Veg Schezwan',
        description: 'Stir-fried vegetables in spicy Schezwan sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: true,
      },
      {
        name: 'Chili Paneer',
        description: 'Fried paneer tossed in spicy chili sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 290,
        popular: true,
      },
      {
        name: 'Hakka Noodles',
        description: 'Stir-fried noodles with vegetables and soy sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 260,
        popular: true,
      },
      {
        name: 'Chicken 65',
        description: 'Crispy fried chicken with Indo-Chinese spices.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Vegetable Spring Roll',
        description: 'Crispy rolls filled with spiced vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Schezwan Fried Rice',
        description: 'Spicy fried rice with vegetables and Schezwan sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Chicken Lollipop',
        description: 'Deep-fried chicken wings with spicy glaze.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Paneer 65',
        description: 'Fried paneer cubes tossed in spicy sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 290,
        popular: false,
      },
      {
        name: 'Peking Duck',
        description: 'Roast duck with crispy skin and hoisin sauce.',
        is_veg: false,
        available_24h: false,
        service_hours: '6:00 PM - 11:00 PM',
        base_price: 800,
        popular: false,
      },
      {
        name: 'Dim Sum',
        description: 'Steamed dumplings with assorted fillings.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 10:00 PM',
        base_price: 300,
        popular: false,
      },
      {
        name: 'Hot and Sour Soup',
        description: 'Spicy and tangy soup with mushrooms and tofu.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 10:00 PM',
        base_price: 200,
        popular: false,
      },
    ],
  },
  {
    category: 'pizza_pasta',
    items: [
      {
        name: 'Tandoori Chicken Pizza',
        description: 'Pizza with tandoori chicken & cheese.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 320,
        popular: true,
      },
      {
        name: 'Paneer Tikka Pizza',
        description: 'Pizza with spiced paneer cubes.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 300,
        popular: true,
      },
      {
        name: 'Butter Chicken Pizza',
        description: 'Pizza topped with butter chicken.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 340,
        popular: true,
      },
      {
        name: 'Masala Margherita',
        description: 'Classic margherita with Indian spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: true,
      },
      {
        name: 'Spicy Lamb Pizza',
        description: 'Pizza with spiced minced lamb.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Masala Alfredo',
        description: 'Creamy pasta with Indian spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Paneer Penne',
        description: 'Penne pasta with spiced paneer.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 300,
        popular: false,
      },
      {
        name: 'Chicken Lasagna',
        description: 'Lasagna layered with chicken tikka.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Masala Pesto',
        description: 'Pasta tossed with Indian spiced pesto.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Margherita Pizza',
        description: 'Classic tomato, mozzarella & basil pizza.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Spaghetti Carbonara',
        description: 'Pasta with egg, cheese & bacon.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Pepperoni Pizza',
        description: 'Pizza topped with pepperoni slices.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: false,
      },
    ],
  },
  {
    category: 'kids_menu',
    items: [
      {
        name: 'Mini Cheese Pizza',
        description: 'Small pizza topped with mozzarella cheese.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 180,
        popular: true,
      },
      {
        name: 'Chicken Nuggets',
        description: 'Breaded fried chicken pieces.',
        is_veg: false,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 150,
        popular: true,
      },
      {
        name: 'Mac & Cheese',
        description: 'Creamy macaroni and cheese.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 160,
        popular: true,
      },
      {
        name: 'Mini Burger',
        description: 'Small beef or veggie burger.',
        is_veg: false,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 170,
        popular: false,
      },
      {
        name: 'Pasta Alfredo',
        description: 'Pasta with creamy Alfredo sauce.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 180,
        popular: false,
      },
      {
        name: 'Grilled Cheese Sandwich',
        description: 'Toasted sandwich with melted cheese.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 140,
        popular: false,
      },
      {
        name: 'French Fries',
        description: 'Crispy deep-fried potato sticks.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 100,
        popular: false,
      },
      {
        name: 'Mini Pancakes',
        description: 'Small fluffy pancakes with syrup.',
        is_veg: true,
        available_24h: true,
        service_hours: '7:00 AM - 11:00 AM',
        base_price: 130,
        popular: false,
      },
      {
        name: 'Fruit Salad',
        description: 'Fresh seasonal fruit mix.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 120,
        popular: false,
      },
      {
        name: 'Chicken Sausages',
        description: 'Grilled chicken sausages.',
        is_veg: false,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Veggie Sticks with Dip',
        description: 'Fresh vegetable sticks with ranch dip.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 110,
        popular: false,
      },
      {
        name: 'Chocolate Milkshake',
        description: 'Creamy chocolate flavored milkshake.',
        is_veg: true,
        available_24h: true,
        service_hours: '11:00 AM - 9:00 PM',
        base_price: 140,
        popular: false,
      },
    ],
  },
  {
    category: 'appetizers',
    items: [
      {
        name: 'Chicken Tikka',
        description: 'Tandoori grilled chicken pieces.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 320,
        popular: true,
      },
      {
        name: 'Paneer Tikka',
        description: 'Grilled spiced cottage cheese cubes.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: true,
      },
      {
        name: 'Seekh Kebab',
        description: 'Minced lamb skewers.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 350,
        popular: true,
      },
      {
        name: 'Hara Bhara Kebab',
        description: 'Spinach & peas patties.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 260,
        popular: false,
      },
      {
        name: 'Fish Amritsari',
        description: 'Batter-fried fish with spices.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 370,
        popular: false,
      },
      {
        name: 'Tandoori Prawns',
        description: 'Spiced grilled prawns.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 400,
        popular: false,
      },
      {
        name: 'Malai Chicken Tikka',
        description: 'Creamy marinated chicken.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 340,
        popular: false,
      },
      {
        name: 'Mutton Galouti',
        description: 'Soft spiced minced lamb kebabs.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 380,
        popular: false,
      },
      {
        name: 'Stuffed Capsicum',
        description: 'Bell peppers stuffed with spiced paneer.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Buffalo Wings',
        description: 'Spicy fried chicken wings.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Bruschetta',
        description: 'Grilled bread with tomato and basil.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 180,
        popular: false,
      },
      {
        name: 'Calamari',
        description: 'Fried squid rings with aioli.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
    ],
  },
  {
    category: 'snacks',
    items: [
      {
        name: 'Samosa',
        description: 'Crispy pastry filled with spiced potatoes.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 80,
        popular: true,
      },
      {
        name: 'Pani Puri',
        description: 'Hollow puris filled with spicy tamarind water.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 90,
        popular: true,
      },
      {
        name: 'Aloo Tikki',
        description: 'Spiced potato patties fried crisp.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 100,
        popular: true,
      },
      {
        name: 'Paneer Pakora',
        description: 'Fried paneer fritters with spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 120,
        popular: false,
      },
      {
        name: 'Chicken 65',
        description: 'Spicy fried chicken bites.',
        is_veg: false,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 180,
        popular: false,
      },
      {
        name: 'Masala Peanuts',
        description: 'Roasted peanuts tossed in spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 70,
        popular: false,
      },
      {
        name: 'Onion Bhaji',
        description: 'Spiced onion fritters.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 110,
        popular: false,
      },
      {
        name: 'Corn Chaat',
        description: 'Spiced boiled corn with lemon and chaat masala.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 90,
        popular: false,
      },
      {
        name: 'Veg Spring Roll',
        description: 'Crispy rolls filled with spiced vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 120,
        popular: false,
      },
      {
        name: 'French Fries',
        description: 'Crispy deep-fried potato sticks.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 100,
        popular: false,
      },
      {
        name: 'Chicken Nuggets',
        description: 'Breaded fried chicken pieces.',
        is_veg: false,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Mozzarella Sticks',
        description: 'Fried cheese sticks with marinara.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 160,
        popular: false,
      },
    ],
  },
  {
    category: 'street_food',
    items: [
      {
        name: 'Pav Bhaji',
        description: 'Spiced vegetable mash served with buttered buns.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 120,
        popular: true,
      },
      {
        name: 'Vada Pav',
        description: 'Spiced potato fritter sandwiched in bread.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 80,
        popular: true,
      },
      {
        name: 'Bhel Puri',
        description: 'Puffed rice with tangy tamarind chutney and spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 90,
        popular: true,
      },
      {
        name: 'Sev Puri',
        description: 'Crispy puris topped with potatoes, chutneys, and sev.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 100,
        popular: false,
      },
      {
        name: 'Dabeli',
        description: 'Spiced mashed potatoes in a bun with pomegranate.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 110,
        popular: false,
      },
      {
        name: 'Frankie Roll',
        description: 'Spiced filling wrapped in thin flatbread.',
        is_veg: false,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 130,
        popular: false,
      },
      {
        name: 'Kachori',
        description: 'Deep-fried spiced lentil-filled pastry.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 90,
        popular: false,
      },
      {
        name: 'Pani Puri',
        description: 'Hollow puris filled with spicy tamarind water.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 90,
        popular: false,
      },
      {
        name: 'Chicken Shawarma',
        description: 'Marinated chicken wrapped in pita bread.',
        is_veg: false,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Masala Corn',
        description: 'Boiled corn tossed with butter and spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 80,
        popular: false,
      },
      {
        name: 'Chaat Platter',
        description: 'Assorted Indian street food snacks.',
        is_veg: true,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 200,
        popular: false,
      },
      {
        name: 'Egg Roll',
        description: 'Spiced egg filling wrapped in paratha.',
        is_veg: false,
        available_24h: true,
        service_hours: '10:00 AM - 10:00 PM',
        base_price: 120,
        popular: false,
      },
    ],
  },
  {
    category: 'biryani_rice',
    items: [
      {
        name: 'Hyderabadi Biryani',
        description:
          'Spiced chicken or lamb layered with fragrant basmati rice.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 360,
        popular: true,
      },
      {
        name: 'Veg Biryani',
        description: 'Basmati rice cooked with mixed vegetables and spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: true,
      },
      {
        name: 'Mutton Biryani',
        description: 'Spiced mutton layered with fragrant basmati rice.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 380,
        popular: true,
      },
      {
        name: 'Paneer Pulao',
        description: 'Fragrant rice cooked with paneer and mild spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Jeera Rice & Dal',
        description: 'Cumin-flavored rice served with tempered lentils.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Kashmiri Pulao',
        description: 'Sweet and aromatic rice with nuts and dry fruits.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Chicken Fried Rice',
        description: 'Indian style fried rice with chicken and spices.',
        is_veg: false,
        available_24h: true,
        service_hours: '',
        base_price: 300,
        popular: false,
      },
      {
        name: 'Lemon Rice',
        description: 'Tangy rice tempered with mustard seeds and peanuts.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Masala Khichdi',
        description: 'Spiced lentil and rice porridge with vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 240,
        popular: false,
      },
      {
        name: 'Fried Rice',
        description: 'Chinese style fried rice with vegetables.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 260,
        popular: false,
      },
      {
        name: 'Risotto',
        description: 'Italian creamy rice dish.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 280,
        popular: false,
      },
      {
        name: 'Paella',
        description: 'Spanish rice with seafood and saffron.',
        is_veg: false,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 400,
        popular: false,
      },
    ],
  },
  {
    category: 'breads',
    items: [
      {
        name: 'Butter Naan',
        description: 'Soft leavened bread baked in tandoor with butter.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 60,
        popular: true,
      },
      {
        name: 'Garlic Naan',
        description: 'Naan topped with garlic and coriander.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 80,
        popular: true,
      },
      {
        name: 'Laccha Paratha',
        description: 'Layered flaky whole wheat bread.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 70,
        popular: true,
      },
      {
        name: 'Tandoori Roti',
        description: 'Whole wheat flatbread baked in tandoor.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 50,
        popular: false,
      },
      {
        name: 'Missi Roti',
        description: 'Spiced gram flour and wheat flour bread.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 70,
        popular: false,
      },
      {
        name: 'Roomali Roti',
        description: 'Thin soft flatbread folded like a handkerchief.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 70,
        popular: false,
      },
      {
        name: 'Stuffed Kulcha',
        description: 'Leavened bread stuffed with spiced potato or paneer.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 90,
        popular: false,
      },
      {
        name: 'Cheese Naan',
        description: 'Naan stuffed with melted cheese.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 110,
        popular: false,
      },
      {
        name: 'Pita Bread',
        description: 'Middle Eastern flatbread.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 80,
        popular: false,
      },
      {
        name: 'Focaccia',
        description: 'Italian flatbread with herbs.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 120,
        popular: false,
      },
      {
        name: 'French Baguette',
        description: 'Crusty long bread.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 130,
        popular: false,
      },
      {
        name: 'Ciabatta',
        description: 'Italian white bread.',
        is_veg: true,
        available_24h: false,
        service_hours: '12:00 PM - 11:00 PM',
        base_price: 140,
        popular: false,
      },
    ],
  },
  {
    category: 'desserts',
    items: [
      {
        name: 'Gulab Jamun',
        description: 'Sweet fried dough balls soaked in rose-flavored syrup.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 120,
        popular: true,
      },
      {
        name: 'Ras Malai',
        description: 'Soft cheese balls in sweetened saffron milk.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 140,
        popular: true,
      },
      {
        name: 'Kheer',
        description: 'Creamy rice pudding flavored with cardamom and nuts.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 130,
        popular: true,
      },
      {
        name: 'Jalebi',
        description: 'Crispy fried spirals soaked in sugar syrup.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 110,
        popular: true,
      },
      {
        name: 'Kulfi',
        description: 'Traditional Indian ice cream with pistachio and saffron.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Gajar Halwa',
        description: 'Carrot pudding cooked with milk and nuts.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 140,
        popular: false,
      },
      {
        name: 'Rabri',
        description: 'Sweet condensed milk dessert flavored with cardamom.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 130,
        popular: false,
      },
      {
        name: 'Mango Shrikhand',
        description: 'Sweetened strained yogurt with mango pulp.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 140,
        popular: false,
      },
      {
        name: 'Chocolate Brownie',
        description: 'Rich and fudgy chocolate cake.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 160,
        popular: false,
      },
      {
        name: 'Cheesecake',
        description: 'Creamy baked dessert with a biscuit base.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 220,
        popular: false,
      },
      {
        name: 'Tiramisu',
        description: 'Coffee-flavored Italian layered dessert.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 240,
        popular: false,
      },
      {
        name: 'Crème Brulee',
        description: 'Rich custard topped with caramelized sugar.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 230,
        popular: false,
      },
    ],
  },
  {
    category: 'beverages',
    items: [
      {
        name: 'Masala Chai',
        description: 'Traditional Indian spiced tea.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 60,
        popular: true,
      },
      {
        name: 'Filter Coffee',
        description: 'Strong South Indian coffee brewed fresh.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 70,
        popular: true,
      },
      {
        name: 'Lassi',
        description: 'Refreshing yogurt-based drink, sweet or salty.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 90,
        popular: true,
      },
      {
        name: 'Jaljeera',
        description: 'Tangy cumin-flavored lemonade.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 80,
        popular: false,
      },
      {
        name: 'Nimbu Pani',
        description: 'Freshly squeezed lemon water with a hint of salt.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 50,
        popular: false,
      },
      {
        name: 'Thandai',
        description: 'Sweet spiced milk drink with nuts.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 110,
        popular: false,
      },
      {
        name: 'Masala Soda',
        description: 'Carbonated soda infused with Indian spices.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 70,
        popular: false,
      },
      {
        name: 'Ginger Tea',
        description: 'Tea brewed with fresh ginger.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 60,
        popular: false,
      },
      {
        name: 'Rose Lassi',
        description: 'Yogurt drink flavored with rose syrup.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 90,
        popular: false,
      },
      {
        name: 'Cappuccino',
        description: 'Espresso topped with steamed milk foam.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 150,
        popular: false,
      },
      {
        name: 'Mojito',
        description: 'Classic mint and lime cocktail.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Lemonade',
        description: 'Freshly squeezed lemon juice with sugar.',
        is_veg: true,
        available_24h: true,
        service_hours: '',
        base_price: 80,
        popular: false,
      },
    ],
  },
  {
    category: 'cocktails',
    items: [
      {
        name: 'Masala Mojito',
        description: 'Classic mojito infused with Indian spices.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 320,
        popular: true,
      },
      {
        name: 'Tamarind Margarita',
        description: 'Margarita with tangy tamarind twist.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 350,
        popular: true,
      },
      {
        name: 'Mango Mule',
        description: 'Moscow mule with fresh mango puree.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 340,
        popular: true,
      },
      {
        name: 'Spiced Gin Tonic',
        description: 'Gin and tonic with Indian spice infusion.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 360,
        popular: true,
      },
      {
        name: 'Rose Martini',
        description: 'Martini with rose and cardamom flavors.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 380,
        popular: true,
      },
      {
        name: 'Indian Punch',
        description: 'Fruity punch with rum and Indian spices.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Coconut Cooler',
        description: 'Refreshing cocktail with coconut and mint.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 320,
        popular: false,
      },
      {
        name: 'Aam Panna Punch',
        description: 'Raw mango punch with rum and spices.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 340,
        popular: false,
      },
      {
        name: 'Kala Khatta Margarita',
        description: 'Margarita with tangy kala khatta syrup.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 360,
        popular: false,
      },
      {
        name: 'Saffron Sour',
        description: 'Whiskey sour infused with saffron.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 370,
        popular: false,
      },
      {
        name: 'Chilli Lemon Margarita',
        description: 'Spicy margarita with chili and lemon.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 350,
        popular: false,
      },
      {
        name: 'Ginger Whiskey Sour',
        description: 'Whiskey sour with fresh ginger infusion.',
        is_veg: true,
        available_24h: false,
        service_hours: '6:00 PM - 2:00 AM',
        base_price: 360,
        popular: false,
      },
    ],
  },
];
