export const menuItems = [
  {
    category: 'breakfast',
    items: [
      {
        name: 'Masala Dosa',
        description:
          'Crispy rice crepe filled with spiced potato mixture, served with sambar and chutneys',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 120,
      },
      {
        name: 'Eggs Benedict',
        description:
          'Poached eggs on toasted English muffin with hollandaise sauce and sautéed spinach',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 180,
      },
      {
        name: 'Belgian Waffles',
        description:
          'Fresh baked waffles with maple syrup, whipped cream and berry compote',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 160,
      },
      {
        name: 'Uttapam Platter',
        description:
          'Three varieties of rice pancakes - onion, tomato, and mixed vegetable',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 150,
      },
      {
        name: 'Avocado Toast',
        description:
          'Sourdough toast with smashed avocado, poached eggs, and chili flakes',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 200,
      },
      {
        name: 'Bircher Muesli',
        description: 'Overnight oats with apple, nuts, and honey yogurt',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 140,
      },
      {
        name: 'English Breakfast',
        description:
          'Eggs, bacon, sausages, grilled tomatoes, mushrooms, baked beans, and toast',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 250,
      },
      {
        name: 'South Indian Platter',
        description:
          'Idli, vada, upma, and kesari bath with chutneys and sambar',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 220,
      },
      {
        name: 'Pancake Stack',
        description:
          'Fluffy buttermilk pancakes with butter and pure maple syrup',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '07:00-11:00',
        base_price: 170,
      },
      {
        name: 'Akuri on Toast',
        description: 'Parsi style scrambled eggs with spices on butter toast',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 160,
      },
    ],
  },
  {
    category: 'appetizers',
    items: [
      {
        name: 'Crispy Calamari',
        description: 'Golden fried squid rings with aioli and spicy marinara',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Bruschetta',
        description:
          'Grilled bread with tomatoes, fresh basil, and extra virgin olive oil',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 180,
      },
      {
        name: 'Dim Sum Basket',
        description: 'Assorted steamed dumplings with soy-ginger sauce',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 320,
      },
      {
        name: 'Paneer Tikka',
        description:
          'Grilled cottage cheese with Indian spices and mint chutney',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Buffalo Wings',
        description: 'Crispy chicken wings tossed in spicy buffalo sauce',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 260,
      },
      {
        name: 'Mezze Platter',
        description: 'Hummus, babaganoush, falafel, and pita bread',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 300,
      },
      {
        name: 'Tempura Prawns',
        description: 'Japanese style battered prawns with wasabi mayo',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 350,
      },
      {
        name: 'Spinach & Artichoke Dip',
        description: 'Creamy dip served with tortilla chips',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 220,
      },
      {
        name: 'Chicken Satay',
        description: 'Grilled chicken skewers with peanut sauce',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Loaded Nachos',
        description:
          'Tortilla chips with cheese, beans, jalapeños, and sour cream',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 250,
      },
    ],
  },
  {
    category: 'soups_salads',
    items: [
      {
        name: 'Classic Caesar Salad',
        description: 'Romaine lettuce, parmesan, croutons with Caesar dressing',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 220,
      },
      {
        name: 'Tom Yum Soup',
        description: 'Thai spicy and sour soup with mushrooms and herbs',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 200,
      },
      {
        name: 'Greek Salad',
        description:
          'Fresh vegetables, olives, feta cheese with olive oil dressing',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Wild Mushroom Soup',
        description: 'Creamy soup with assorted wild mushrooms',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 180,
      },
      {
        name: 'Quinoa Buddha Bowl',
        description:
          'Mixed greens, quinoa, roasted vegetables, tahini dressing',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '11:00-23:00',
        base_price: 280,
      },
      {
        name: 'Seafood Chowder',
        description: 'Creamy soup with mixed seafood and vegetables',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '11:00-23:00',
        base_price: 320,
      },
      {
        name: 'Caprese Salad',
        description: 'Fresh mozzarella, tomatoes, basil with balsamic glaze',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 260,
      },
      {
        name: 'Lentil Soup',
        description: 'Hearty soup with mixed lentils and vegetables',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 160,
      },
      {
        name: 'Cobb Salad',
        description: 'Mixed greens, chicken, bacon, egg, avocado, blue cheese',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 300,
      },
      {
        name: 'Miso Soup',
        description: 'Traditional Japanese soup with tofu and seaweed',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 140,
      },
    ],
  },
  {
    category: 'indian_main_course',
    items: [
      {
        name: 'Butter Chicken',
        description: 'Tender chicken in rich tomato-butter gravy',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 340,
      },
      {
        name: 'Paneer Butter Masala',
        description: 'Cottage cheese in creamy tomato gravy',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Dal Makhani',
        description: 'Black lentils slow-cooked with cream and spices',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Biryani',
        description:
          'Fragrant rice with choice of chicken/vegetables and aromatic spices',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 320,
      },
      {
        name: 'Rogan Josh',
        description: 'Kashmiri style lamb curry with authentic spices',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 380,
      },
      {
        name: 'Palak Paneer',
        description: 'Cottage cheese cubes in spiced spinach gravy',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 260,
      },
      {
        name: 'Fish Curry',
        description: 'Coastal style fish curry with coconut base',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 360,
      },
      {
        name: 'Chole Bhature',
        description: 'Spiced chickpeas with deep-fried bread',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 220,
      },
      {
        name: 'Mixed Vegetable Curry',
        description: 'Seasonal vegetables in rich gravy',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Chicken Tikka Masala',
        description: 'Grilled chicken pieces in spiced tomato gravy',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 320,
      },
    ],
  },
  {
    category: 'continental_main_course',
    items: [
      {
        name: 'Grilled Salmon',
        description: 'Norwegian salmon with herb butter sauce',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 450,
      },
      {
        name: 'Beef Tenderloin',
        description: 'Grilled beef with red wine reduction',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '19:00-23:00',
        base_price: 520,
      },
      {
        name: 'Mushroom Risotto',
        description: 'Creamy Italian rice with wild mushrooms',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Chicken Confit',
        description: 'Slow-cooked chicken with roasted vegetables',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '19:00-23:00',
        base_price: 380,
      },
      {
        name: 'Ratatouille',
        description: 'French style baked vegetables with herbs',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 260,
      },
      {
        name: 'Sea Bass',
        description: 'Pan-seared sea bass with lemon butter sauce',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '19:00-23:00',
        base_price: 480,
      },
      {
        name: 'Vegetable Lasagna',
        description: 'Layered pasta with vegetables and cheese',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 320,
      },
      {
        name: 'Pork Chops',
        description: 'Grilled pork with apple sauce',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '19:00-23:00',
        base_price: 400,
      },
      {
        name: 'Gnocchi',
        description: 'Potato dumplings in sage butter sauce',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 300,
      },
      {
        name: 'Duck Confit',
        description: 'Classic French style duck leg confit',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '19:00-23:00',
        base_price: 550,
      },
    ],
  },
  {
    category: 'asian_specialties',
    items: [
      {
        name: 'Pad Thai',
        description:
          'Thai rice noodles with tofu/chicken, peanuts and tamarind sauce',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Sushi Platter',
        description: 'Assorted nigiri and maki rolls with wasabi',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 450,
      },
      {
        name: 'Kung Pao Chicken',
        description: 'Spicy diced chicken with peanuts and vegetables',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 320,
      },
      {
        name: 'Vietnamese Pho',
        description: 'Rice noodle soup with herbs and choice of protein',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '11:00-23:00',
        base_price: 300,
      },
      {
        name: 'Korean Bibimbap',
        description: 'Mixed rice bowl with vegetables and fried egg',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 290,
      },
      {
        name: 'Mapo Tofu',
        description: 'Spicy tofu in Sichuan pepper sauce',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 260,
      },
      {
        name: 'Malaysian Laksa',
        description: 'Spicy coconut noodle soup with seafood',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 340,
      },
      {
        name: 'Dimsum Platter',
        description: 'Assorted steamed dumplings with dipping sauces',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 380,
      },
      {
        name: 'Japanese Ramen',
        description: 'Noodle soup with chashu pork and soft boiled egg',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '11:00-23:00',
        base_price: 320,
      },
      {
        name: 'Thai Green Curry',
        description: 'Aromatic coconut curry with vegetables/chicken',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 300,
      },
    ],
  },
  {
    category: 'pizza_pasta',
    items: [
      {
        name: 'Margherita Pizza',
        description: 'Classic tomato sauce, mozzarella and basil',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'Pepperoni Pizza',
        description: 'Spicy pepperoni with mozzarella and tomato sauce',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 320,
      },
      {
        name: 'Penne Arrabbiata',
        description: 'Spicy tomato sauce with garlic and herbs',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 260,
      },
      {
        name: 'Fettuccine Alfredo',
        description: 'Creamy parmesan sauce with garlic',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 280,
      },
      {
        name: 'BBQ Chicken Pizza',
        description: 'Grilled chicken with BBQ sauce and red onions',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 340,
      },
      {
        name: 'Seafood Pasta',
        description: 'Mixed seafood in white wine sauce',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 380,
      },
      {
        name: 'Four Cheese Pizza',
        description: 'Blend of mozzarella, gorgonzola, parmesan, and ricotta',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 360,
      },
      {
        name: 'Pesto Pasta',
        description: 'Fresh basil pesto with pine nuts and parmesan',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 290,
      },
      {
        name: 'Supreme Pizza',
        description: 'Loaded with vegetables and mixed meats',
        is_veg: false,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 380,
      },
      {
        name: 'Lasagna',
        description: 'Layered pasta with meat sauce and cheese',
        is_veg: false,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 340,
      },
    ],
  },
  {
    category: 'desserts',
    items: [
      {
        name: 'Tiramisu',
        description: 'Classic Italian coffee-flavored dessert',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 220,
      },
      {
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with molten center',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Crème Brûlée',
        description: 'Classic French vanilla custard with caramelized sugar',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 220,
      },
      {
        name: 'Apple Pie',
        description: 'Warm apple pie with vanilla ice cream',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 200,
      },
      {
        name: 'Cheesecake',
        description: 'New York style with berry compote',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
      {
        name: 'Ice Cream Selection',
        description: 'Choice of three scoops with toppings',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 180,
      },
      {
        name: 'Gulab Jamun',
        description: 'Indian milk dumplings in sugar syrup',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 160,
      },
      {
        name: 'Fruit Pavlova',
        description: 'Meringue with fresh cream and fruits',
        is_veg: true,
        is_available_24_7: false,
        service_hours: '12:00-23:00',
        base_price: 260,
      },
      {
        name: 'Belgian Waffle',
        description: 'With chocolate sauce and ice cream',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 220,
      },
      {
        name: 'Sticky Toffee Pudding',
        description: 'Warm date pudding with toffee sauce',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 240,
      },
    ],
  },
  {
    category: 'beverages',
    items: [
      {
        name: 'Fresh Fruit Juices',
        description: 'Selection of seasonal fruits',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 120,
      },
      {
        name: 'Specialty Coffee',
        description: 'Espresso, Cappuccino, Latte, etc.',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 140,
      },
      {
        name: 'Classic Mojito',
        description: 'Mint, lime, and soda refresher',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 160,
      },
      {
        name: 'Smoothies',
        description: 'Blend of fruits and yogurt',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 150,
      },
      {
        name: 'Iced Teas',
        description: 'Various flavored cold teas',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 130,
      },
      {
        name: 'Lassi',
        description: 'Sweet or salted yogurt drink',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 120,
      },
      {
        name: 'Milkshakes',
        description: 'Classic flavors with ice cream',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 180,
      },
      {
        name: 'Virgin Colada',
        description: 'Pineapple and coconut cream blend',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 170,
      },
      {
        name: 'Mineral Water',
        description: 'Still or sparkling',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 80,
      },
      {
        name: 'Soft Drinks',
        description: 'Selection of sodas',
        is_veg: true,
        is_available_24_7: true,
        service_hours: '24 Hours',
        base_price: 90,
      },
    ],
  },
];
